# Generated by Django 4.2.8 on 2023-12-28 10:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("description", models.TextField(max_length=200)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
