# Generated by Django 4.2.8 on 2024-01-10 09:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("departments", "0002_department_archived_department_modified_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="department",
            old_name="create_at",
            new_name="created_at",
        ),
    ]
