# Generated by Django 4.2.8 on 2024-01-10 09:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0002_contact_archived_contact_modified_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="create_at",
            new_name="created_at",
        ),
    ]
