# Generated by Django 4.2.8 on 2024-01-10 09:42

from django.db import migrations, models
import employees.validate.validation_employee


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0002_employee_archived_employee_modified_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employee",
            old_name="create_at",
            new_name="created_at",
        ),
        migrations.AlterField(
            model_name="employee",
            name="birthday",
            field=models.DateField(
                validators=[employees.validate.validation_employee.validate_age]
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="email",
            field=models.EmailField(
                max_length=100,
                unique=True,
                validators=[employees.validate.validation_employee.validate_email],
            ),
        ),
    ]
