# Generated by Django 4.2.8 on 2024-01-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0003_rename_create_at_employee_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="email",
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
